const actionTypes = {
  cart: {
    ADD_PRODUCT: 'ADD_PRODUCT',
    CLEAR_CART: 'CLEAR_CART',
    REMOVE_PRODUCT: 'REMOVE_PRODUCT',
    SUBTRACT_PRODUCT: 'SUBTRACT_PRODUCT',
    TOGGLE_DROPDOWN: 'TOGGLE_DROPDOWN'
  },
  user: {
    SET_CURRENT_USER: 'SET_CURRENT_USER'
  },
  store: {
    UPDATE_CATEGORIES: 'UPDATE_CATEGORIES',
    UPDATE_PRODUCTS: 'UPDATE_PRODUCTS'
  }
}

export default actionTypes
